services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000  <-- OLD DEV COMMAND
    # NEW PRODUCTION COMMAND:
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Share static files with Nginx
    expose:
      - "8000"  # Only expose to Nginx, not the outside world
    depends_on:
      - db
    environment:
      - DEBUG=0  # Turn off Debug for production!
      - SECRET_KEY=your_secret_key_here
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_HOST=db
      - DB_NAME=metro_db
      - DB_USER=admin
      - DB_PASSWORD=password
      - EMAIL_USER=${EMAIL_USER} 
      - EMAIL_PASS=${EMAIL_PASS}
      - DEBUG=0
      - SECRET_KEY=any-random-string
      - ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"  # The public port
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles # Read static files from here
    depends_on:
      - web

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=metro_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
  static_volume:  # The shared storage for CSS/Images